#!/usr/bin/env node
// Compiles content/*.json into portfolio-data.js (the runtime data file).
// No deps — uses Node built-ins only.
import { readFile, readdir, writeFile } from "node:fs/promises";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const here = dirname(fileURLToPath(import.meta.url));
const root = join(here, "..");
const contentDir = join(root, "content");
const outFile = join(root, "portfolio-data.js");

async function readJson(path) {
  const text = await readFile(path, "utf8");
  try {
    return JSON.parse(text);
  } catch (err) {
    throw new Error(`Invalid JSON in ${path}: ${err.message}`);
  }
}

async function loadCaseStudies() {
  const dir = join(contentDir, "case-studies");
  const files = (await readdir(dir)).filter((f) => f.endsWith(".json"));
  const items = await Promise.all(files.map((f) => readJson(join(dir, f))));
  items.sort((a, b) => (a.order ?? 0) - (b.order ?? 0));
  return items.map(({ order: _order, ...rest }) => stripFalse(rest));
}

// Drop boolean fields that are exactly `false` so the runtime shape matches the
// previous hand-edited file (where `featured`/`half` only appeared when true).
function stripFalse(obj) {
  const out = {};
  for (const [k, v] of Object.entries(obj)) {
    if (v === false && (k === "featured" || k === "half")) continue;
    out[k] = v;
  }
  return out;
}

async function build() {
  const [meta, hero, authority, liveStrip, services, cta, deepCase, skills, about, contact, commands, caseStudies] =
    await Promise.all([
      readJson(join(contentDir, "meta.json")),
      readJson(join(contentDir, "hero.json")),
      readJson(join(contentDir, "authority.json")),
      readJson(join(contentDir, "live-strip.json")),
      readJson(join(contentDir, "services.json")),
      readJson(join(contentDir, "cta.json")),
      readJson(join(contentDir, "deep-case.json")),
      readJson(join(contentDir, "skills.json")),
      readJson(join(contentDir, "about.json")),
      readJson(join(contentDir, "contact.json")),
      readJson(join(contentDir, "commands.json")),
      loadCaseStudies(),
    ]);

  const data = {
    meta,
    hero,
    authority: authority.items,
    liveStrip: liveStrip.cells,
    services,
    cta,
    caseStudies,
    deepCase,
    skills: skills.groups,
    about,
    contact,
    commands: commands.items,
  };

  const banner =
    "// Generated by tools/build-data.mjs from content/*.json — DO NOT EDIT BY HAND.\n" +
    "// To change content, edit the JSON files under content/ (or use the admin UI),\n" +
    "// then run `npm run build:data`.\n\n";
  const body = `window.PORTFOLIO_DATA = ${JSON.stringify(data, null, 2)};\n`;
  await writeFile(outFile, banner + body, "utf8");
  return outFile;
}

build()
  .then((path) => {
    process.stdout.write(`Wrote ${path}\n`);
  })
  .catch((err) => {
    process.stderr.write(`build:data failed — ${err.message}\n`);
    process.exit(1);
  });
