#!/usr/bin/env node
// Compiles content/*.json into portfolio-data.js (the runtime data file).
// No deps — uses Node built-ins only.
import { readFile, readdir, writeFile } from "node:fs/promises";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const here = dirname(fileURLToPath(import.meta.url));
const root = join(here, "..");

async function readJson(path) {
  const text = await readFile(path, "utf8");
  try {
    return JSON.parse(text);
  } catch (err) {
    throw new Error(`Invalid JSON in ${path}: ${err.message}`);
  }
}

async function loadCaseStudies(contentDir) {
  const dir = join(contentDir, "case-studies");
  const files = (await readdir(dir)).filter((f) => f.endsWith(".json"));
  const items = await Promise.all(files.map((f) => readJson(join(dir, f))));
  items.sort((a, b) => (a.order ?? 0) - (b.order ?? 0));
  return items.map(({ order: _order, ...rest }) => stripFalse(rest));
}

// Drop boolean fields that are exactly `false` so the runtime shape matches the
// previous hand-edited file (where `featured`/`half` only appeared when true).
function stripFalse(obj) {
  const out = {};
  for (const [k, v] of Object.entries(obj)) {
    if (v === false && (k === "featured" || k === "half")) continue;
    out[k] = v;
  }
  return out;
}

async function buildLocale(locale) {
  const contentDir = locale === "en"
    ? join(root, "content")
    : join(root, "content", locale);
  const outFile = locale === "en"
    ? join(root, "portfolio-data.js")
    : join(root, `portfolio-data-${locale}.js`);

  const [meta, hero, authority, liveStrip, services, cta, faq, testimonial, deepCase, skills, about, contact, commands, insights, caseStudies] =
    await Promise.all([
      readJson(join(contentDir, "meta.json")),
      readJson(join(contentDir, "hero.json")),
      readJson(join(contentDir, "authority.json")),
      readJson(join(contentDir, "live-strip.json")),
      readJson(join(contentDir, "services.json")),
      readJson(join(contentDir, "cta.json")),
      readJson(join(contentDir, "faq.json")),
      readJson(join(contentDir, "testimonial.json")),
      readJson(join(contentDir, "deep-case.json")),
      readJson(join(contentDir, "skills.json")),
      readJson(join(contentDir, "about.json")),
      readJson(join(contentDir, "contact.json")),
      readJson(join(contentDir, "commands.json")),
      readJson(join(contentDir, "insights.json")),
      loadCaseStudies(contentDir),
    ]);

  const data = {
    locale,
    dir: locale === "ar" ? "rtl" : "ltr",
    meta,
    hero,
    authority: authority.items,
    liveStrip: liveStrip.cells,
    services,
    cta,
    faq,
    testimonial,
    caseStudies,
    deepCase,
    skills: skills.groups,
    about,
    contact,
    commands: commands.items,
    insights,
  };

  const banner =
    `// Generated by tools/build-data.mjs from content/${locale === "en" ? "" : locale + "/"}*.json — DO NOT EDIT BY HAND.\n` +
    "// To change content, edit the JSON files (or use the admin UI),\n" +
    "// then run `npm run build:data`.\n\n";
  const body = `window.PORTFOLIO_DATA = ${JSON.stringify(data, null, 2)};\n`;
  await writeFile(outFile, banner + body, "utf8");
  return outFile;
}

async function build() {
  const locales = ["en"];
  // Optional locales: include only if their content tree exists.
  for (const locale of ["ar"]) {
    try {
      await readJson(join(root, "content", locale, "meta.json"));
      locales.push(locale);
    } catch {
      // tree missing — skip silently
    }
  }
  const out = [];
  for (const locale of locales) out.push(await buildLocale(locale));
  return out;
}

build()
  .then((paths) => {
    for (const p of paths) process.stdout.write(`Wrote ${p}\n`);
  })
  .catch((err) => {
    process.stderr.write(`build:data failed — ${err.message}\n`);
    process.exit(1);
  });
